name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.3.2", "1.5.0"]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup poetry
        run: pipx install poetry==${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Tests
        run: make -o pre-commit test
      - name: Get Coveraage
        uses: orgoro/coverage@v3
        with:
          coverageFile: .coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
